print('hello,world!라고 할줄 알았지?')
print('hello,world!라고 할줄 알았지?')
print('hello,world!라고 할줄 알았지?')
print('hello,world!라고 할줄 알았지?')
print('hello,world!라고 할줄 알았지?')
print('hello,world!라고 할줄 알았지?')
print('hello,world!라고 할줄 알았지?')
print('hello,world!라고 할게')